=head1 Body Methods

These methods are accessible via the C</body> URL.


=head2 get_body ( session_id, body_id )

Returns detailed statistics about an empire.

 {
    "id" : "id-goes-here",
    "x" : -4,
    "y" : 10,
    "z" : 6,
    "star_id" : "id-goes-here",
    "orbit" : 3,
    "type" : "habitable planet",
    "name" : "Earth",
    "image" : "p13",
    "size" : 67,
    "water" : 900,
    "ore" : {
        "gold" : 3399,
        "bauxite" : 4000,
        ...
    },
    
    --------- if you own the planet the data below will be included ---------
    
    "building_count" : 7,
    "happiness" : 3939,
    "happiness_hour" : 25,
    "food_stored" : 33329,
    "food_capacity" : 40000,
    "food_hour" : 229,
    "energy_stored" : 39931,
    "energy_capacity" : 43000,
    "energy_hour" : 391,
    "ore_hour" 284,
    "ore_capacity" 35000,
    "ore_stored" 1901,
    "waste_hour" : 933,
    "waste_stored" : 9933,
    "waste_capacity" : 13000,
    "water_stored" : 9929,
    "water_hour" : 295,
    "water_capacity" : 51050,
 }
 
=head3 session_id

A session id.

=head3 body_id

The id of the body you wish to retrieve.


=head2 get_buildings ( session_id, body_id )

Retrieves a list of the buildings on a planet. 

 {
    "buildings" : {
        "id-goes-here" : {
            "name" : "Apple Orchard",
            "x" : 1,
            "y" : -1,
            "url" : "/apple",
            "level" : 3,
            "image" : "apple",
        },
        "id-goes-here2" : {
            "name" : "Planetary Command",
            "x" : 0,
            "y" : 0,
            "url" : "/command",
            "level" : 1,
            "image" : "command",
        }
    },
    "status" : { get_status() }
 }

Throws 1002 and 1010.

=head3 session_id

A session id.

=head3 body_id

The id of the body you wish to retrieve the buildings on.



=head2 get_buildable ( session_id, body_id, x, y ) 

Provides a list of all the building types that are available to be built on a given space on a planet.

 {
    "buildable" : {
        "Wheat Farm" : "/wheat",
        "Apple Orchard" : "/apple"
    },
    "status" : { get_status() }
 }


Throws 1002, 1010, 1011, and 1012, and 1013.

=head3 session_id

A session id.

=head3 body_id

The id of the body you wish to retrieve the buildings on.

=head3 x

The x axis of the area on the planet you wish to place the building. Valid values are between -5 and 5 inclusive.

=head3 y

The y axis of the area on the planet you wish to place the building. Valid values are between -5 and 5 inclusive.






=head2 rename_body ( session_id, body_id, name )

Renames a body, provided the empire attached to the session owns the body. Returns a 1 on success.

Throws 1000, 1002 and 1010.

=head3 session_id

A session id.

=head3 body_id

The id of the body you wish to rename.

=head3 name

The new name of the body.

=cut

