
=head1 What are API keys?

A Client Key (or just Client Key) is a string that uniquely identifies a client (like the web client vs the iPhone client) to the server. 


=head1 Why are client keys needed?

Client keys allow us to track which clients are being used for what purpose. 


=head1 Where in the API are client keys used?

They are only used on methods that create a session, such as C<login> and C<found> in L<Empire>.


=head1 How do I get a client key?



=cut
