=head1 Development Methods

Development is accessible via the URL C</development>.

The higher the development ministry, the more builds you can put in your build queue.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session, building_id )

This method is extended to include details about what's in your build queue.

 {
    "building" : { ... },
    "status" : { ... },
    "build_queue" : [
        {
            "building_id" : "building-id-goes-here",
            "name" : "Planetary Commmand",
            "to_level" : 9,
            "seconds_remaining" : 537,
            "x" : 0,
            "y" : 0
        },
        {
            "building_id" : "building-id-goes-here",
            "name" : "Wheat Farm",
            "to_level" : 15,
            "seconds_remaining" : 9748,
            "x" : -1,
            "y" : 4
        }
    ],
    "subsidy_cost" : 8 # the essentia cost to subsidize the build queue
 }
 
=head2 subsidize_build_queue ( session_id, building_id )

Allows a player to instantly finish any buildings in their build queue. The cost is returned by the C<view> method. Returns:

 {
    "status" : { ... },
    "essentia_spent" : 8
 }

=head3 session_id

A session id.

=head3 building_id

The id of the development ministry.
 
=cut