=head1 Embassy Diagram

The Embassy is a complex beast, so to help you wrap your brain around it we've created a little flow diagram of how the methods come together.

=begin html

<img src="Embassy.png">
<br>
<a href="Embassy.graffle">OmniGraffle Version</a>

=end html

=head1 Embassy Methods

Embassy is accessible via the URL C</embassy>. The embassy is used to form alliances with other players.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.



=head2 view ( session_id, building_id )

Same as view in L<Buildings> except:

 {
    "status" : { ... },
    "building" : { ... },
    "alliance_status" : { get_alliance_status() }
 }

We add an C<alliance_status> block if this empire is in an alliance. It contains the same information as C<get_alliance_status>


=head2 create_alliance ( session_id, building_id, name )

Create a new alliance. Returns the same output as C<get_alliance_status>.

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 name

A unique name for this alliance. Must be between 3 and 30 characters, cannot contain profanity or restricted characters.




=head2 dissolve_alliance ( session_id, building_id )

Can only be called by alliance leader. Disbands an existing alliance.

NOTE: All space stations associated with the alliance will be abandoned and converted to asteroids.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.



=head2 get_alliance_status ( session_id, building_id )

Returns everything about an alliance that members should know.

 {
    "status" : { ... },
    "alliance" : {
        "id" : "id-goes-here",
        "name" : "United Federation of Planets",
        "members" : [
            {
                "empire_id" : "id goes here",
                "name" : "Klingons",
            }
            ...
        ],
        "leader_id" : "id goes here",
        "forum_uri" : "http://forum.example.com/",
        "description" : "This is public information.",
        "announcements" : "This is private information.",
        "date_created" : "01 31 2010 13:09:05 +0600"
     }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.





=head2 send_invite ( session_id, building_id, invitee_id, [ message ] )

Can only be called by alliance leader. Invite an empire to an alliance.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 invitee_id

The unique id of an empire you'd like to invite to an alliance. See L<Empire/"search_empires"> to look up empire ids.

=head3 message

Optional. A personalized welcome message that will be included in the invitation.






=head2 withdraw_invite ( session_id, building_id, invite_id, [ message ] )

Can only be called by alliance leader. Delete an invitation.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 invite_id

The unique id of an invitation. See C<get_pending_invites> for details.

=head3 message

Optional. A personalized message that will be sent to the user about why their invitation has been withdrawn.





=head2 accept_invite ( session_id, building_id, invite_id, [ message ] )

Accept an invitation. Returns the same output as C<get_alliance_status>.

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 invite_id

The unique id of an invitation. See C<get_my_invites> for details.

=head3 message

Optional. A personalized message that will be sent to the alliance leader with your acceptance.





=head2 reject_invite ( session_id, building_id, invite_id, [ message ] )

Delete an invitation.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 invite_id

The unique id of an invitation. See C<get_my_invites> for details.

=head3 message

Optional. A personalized message that will be sent to the alliance leader along with your rejection.




=head2 get_pending_invites ( session_id, building_id )

Can only be called by the alliance leader. Returns a list of invitations that have been sent out, but that have not been accepted, rejected, or withdrawn.

 {
    "status" : { ... },
    "invites" : [
        {
            "id" : "id-goes-here",
            "name" : "The Borg",
            "empire_id" : "id-goes-here"
        },
        ...
    ]
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.




=head2 get_my_invites ( session_id, building_id )

Returns a list of invitations that have been offered to this empire.

 {
    "status" : { ... },
    "invites" : [
        {
            "id" : "id-goes-here",
            "name" : "United Federation of Planets",
            "alliance_id" : "id-goes-here"
        },
        ...
    ]
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.



=head2 assign_alliance_leader ( session_id, building_id, new_leader_id )

Sets a new empire to lead the alliance. Can only be called by the current alliance leader. Returns the same thing as C<get_alliance_status>.

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 new_leader_id

The unique id of an empire that will lead the alliance going forward. The empire must already be a member of the alliance.



=head2 update_alliance ( session_id, building_id, params )

Updates the properties of an alliance. Returns the same thing as C<get_alliance_status>. Can only be called by the alliance leader.

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 params

A hash reference of alliance properties. None of which can contain profanity or restricted characters. You can update any or all of these properties at the same time.

=over

=item forum_uri

The URI to a forum where alliance discussion occurs.

=item description

Information that is publcily available about an alliance.

=item announcements

Information that is only available to alliance members.

=back


=head2 leave_alliance ( session_id, building_id, [ message ] )

A member of an alliance revokes their own membership.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 message

An optional message about why you're leaving the alliance. Cannot contain restricted characters or profanity.



=head2 expel_member ( session_id, building_id, empire_id, [ message ] )

Forcibly removes a member from an alliance. Returns the same thing as C<get_alliance_status>. Can only be called by the alliance leader.

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 empire_id

The unique id of the empire to remove from the alliance.

=head3 message

An optional message about why you're removing them from the alliance. Cannot contain restricted characters or profanity.



=head2 view_stash ( session_id, building_id )

Returns a list of what is in the current stash:

 {
    "status" : { ... },
    "stash" : {                # what is stored in the stash
        "gold" : 4500,
        "water" : 1000,
        "apple" : 8
    },
    "stored" : {               # what is stored in planetary storage
        "energy" : 40000,
        "algae" : 43000,
        "water" : 19000,
        "bauxite" : 1110,
        "galena" : 33120
    },
    "max_exchange_size" : 30000,
    "exchanges_remaining_today" : 1
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.





=head2 donate_to_stash ( session_id, building_id, donation )

Returns C<view_stash>

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 donation

A hash reference containing name value pairs of the resources you want to put into the stash from your planet.

B<NOTE:> Cannot donate waste.

 {
    "water" : 4500,
    "bread" : 5000
 }





=head2 exchange_with_stash ( session_id, building_id, donation, request )

Returns C<view_stash>

=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.

=head3 donation

A hash reference containing name value pairs of the resources you want to put into the stash from your planet.

B<NOTE:> Cannot donate waste.

 {
    "water" : 4500,
    "bread" : 5000
 }

=head3 request

A hash reference containing name value pairs of the resources you want to pull from the stash stash onto your planet.

B<NOTE:> The total sum, must add up to the sum of the donation, but can be in different concentrations.

 {
    "energy" : 2000,
    "meal" : 7500
 }

=head2 view_propositions (session_id, building_id )

Returns a list of the pending propositions.

 {
    "status" : { ... },
    "propositions" : [
        {
           "id" : "id-goes-here",
           "name" : "Rename Station",
           "description" : "Rename the station from 'Bri Prui 7' to 'Deep Space 1'.",
           "votes_needed" : 7,
           "votes_yes" : 1,
           "votes_no" : 0,
           "status" : "Pending",
           "date_ends" : "01 31 2010 13:09:05 +0600",
           "proposed_by" : {
                "id" : "id-goes-here",
                "name" : "Klingons",
           },
           "my_vote" : 0 # not present if they haven't voted
        },
        ...
    ]
 }
 
=head3 session_id

A session id.

=head3 building_id

The unique id of the embassy.


=head2 cast_vote ( session_id, building_id, proposition_id, vote )

Casts a vote for or against a proposition.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Rename Station",
        "description" : "Rename the station from 'Bri Prui 7' to 'Deep Space 1'.",
        "votes_needed" : 7,
        "votes_yes" : 2,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Klingons",
        },
        "my_vote" : 0 # not present if they haven't voted
    }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 proposition_id

The id of the propostion you're casting this vote for or against. See C<view_propositions> for a list.

=head3 vote

A boolean indicating which way you wish to vote. 1 for yes. 0 for no. Default is 0.




=cut
