=head1 Empire Methods

The following methods are available from C</empire>.

=head2 is_name_available ( name ) 

Returns a 1 if the name is available, or a 0 if it is not.

=head3 name

The name of the empire to search for.



=head2 logout ( session_id )

Ends a session. Returns 1.

Throws 1006.

=head3 session_id

A session id.



=head2 login ( name, password )

Returns a session id after confirming the password matches the empire.

Throws 1004 and 1005.

=head3 name

The name of the empire.

=head3 password

The password to authenticate to the empire.



=head2 create ( params ) 

Creates a new empire and then returns a hash reference with a session and an empire_id.

 {
    empire_id   => '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
    session_id  => '7ba7b80d-91d1-b0b3-1111-10c04fd430cd'
 }

Throws 1000, 1001, 1002.

=head3 params

A hash of parameters.

=head4 name

The name of the empire to create. Required.

=head4 password

The password to log in to the empire. Required.

=head4 password1

Retyping the password again. This must match C<password> to succeed.

=head4 species_id

The id of the species that rules this empire. Defaults to 'human_species' (Human).




=cut
