=head1 Food Reserve Methods

Food Reserve is accessible via the URL C</foodreserve>.

The food reserve stores the excess food you produce.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session_id, building_id )

This method is extended to include details about what kind of food is stored.

 {
    "building" : { ... },
    "status" : { ... },
    "food_stored" : {
        "apple" : 0,
        "bread" : 47,
        "algae" : 301,
        ...
    }
 }
 
 
=head2 dump ( session_id, building_id, type, amount )

Converts food into waste.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the building.

=head3 type

Choose a type of food convert into waste. (apple, corn, burger, etc)

=head3 amount

An integer representing the amount to dump.



=cut