=head1 Intelligence Methods

Intelligence Ministry is accessible via the URL C</intelligence>.

The Intelligence Ministry is where you build and control your spies.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session_id, building_id )

 {
    "status" : { ... },
    "building" : { ... },
    "spies" : {
        "maximum" : 5,
        "current" : 1,
        "training_costs" : {
            "food" : 100,
            "water" : 120,
            "energy" : 20,
            "ore" : 5,
            "waste" : 10,
            "time" : 60,
        }
    },
 }
 

=head2 train_spy ( session_id, building_id, [ quantity ])

Allows you to train more spies.

 {
    "status" : { ... },
    "trained" : 3,
    "not_trained" : 2
 }
 
The only reason C<not_trained> might be over 0 is if you specify training more spies than you have resources to spend.

Throws 1013, 1009.

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 quantity

An integer between 1 and 5. Defaults to 1.


=head2 view_spies ( session_id, building_id, [ page_number ] )

Returns the list of spies you have on your roster.

 {
    "status" : { ... },
    "spies" : [
        {
            "id" : "id-goes-here",
            "name" : "Jason Bourne",
            "assignment" : "Idle",
            "level" : 9,
            "politics" : 0,                         # experience in handling happiness
            "mayhem" : 20,                          # experience in handling missions involving murder and destruction
            "theft" : 40,                           # experience in handling missions involving stealing items
            "intel" : 33,                           # experience in handling missions involving information and spies
            "offense_rating" : 570,
            "defense_rating" : 150,
            "assigned_to" : {
                "body_id" : "id-goes-here",
                "name" : "Earth",
            },
            "is_available" : 1, # can be reassigned
            "available_on" : "01 31 2010 13:09:05 +0600", # if can't be reassigned, this is when will be available
            "started_assignment" : "01 31 2010 13:09:05 +0600",
            "seconds_remaining" : 45
        },
        ...
    ],
    "spy_count" : 12,
    "possible_assignments" : [
        'Idle',
        'Gather Intelligence',
        ...
    ]
 }

Take a look at the C<assign_spy> method below for assignment descriptions.

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 page_number

Defaults to 1. An integer representing which page to view. Shows 25 spies per page.



=head2 burn_spy ( session_id, building_id, spy_id )

Allows you to eliminate one of your spies from your payroll.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 spy_id

The unique id of the spy you wish to burn.


=head2 name_spy ( session_id, building_id, spy_id, name )

Set the name of the spy. Returns:

 {
    "status" : { ... }
 }
 
Throws 1002, 1005, 1013.

=head3 session_id

A session id.

=head3 building_id

The unique id of the intelligence building.

=head3 spy_id

The unique id of the spy you wish to train.

=head3 name

The name you'd like to set for the spy. The name cannot contain @, <, #, &, ; or profanity, and must be at least 1 character long.



=head2 assign_spy ( session_id, building_id, spy_id, assignment )

Set a spy on a new task.

 {
    "status" : { ... },
    "mission" : {
        "result" : "Failure",
        "message_id" : "id-goes-here",
        "reason" : "I'm under heavy fire over here!"
    },
    "spy" : {
        "id" : "id-goes-here",
        "name" : "Jason Bourne",
        "assignment" : "Idle",
        "level" : 9,
        "politics" : 0,                         # experience in handling happiness
        "mayhem" : 20,                          # experience in handling missions involving murder and destruction
        "theft" : 40,                           # experience in handling missions involving stealing items
        "intel" : 33,                           # experience in handling missions involving information and spies
        "offense_rating" : 570,
        "defense_rating" : 150,
        "assigned_to" : {
            "body_id" : "id-goes-here",
            "name" : "Earth",
        },
        "is_available" : 1, # can be reassigned
        "available_on" : "01 31 2010 13:09:05 +0600", # if can't be reassigned, this is when will be available
        "started_assignment" : "01 31 2010 13:09:05 +0600",
        "seconds_remaining" : 45
    }
 }
 
The mission block allows you to give immediate feedback to the player. The C<result> types that can be sent back are:

=over

=item Accepted

This is provided when no immediate mission occurs. For example, if you set a spy to "Idle" or "Counter Espionage".

=item Success

This means a mission has occurred and came out in favor of the spy.

=item Bounce

This means a mission started, but was foiled and neither side won.

=item Failure

This means a mission occurred, but went so poorly that the defense got the upper hand and bested you.

=back

The C<reason> provides a message in sentence form about why a spy won or lost a mission. This message is related to the success or failure, not any outcome that results from that success or failure.

The C<message_id> refers to a message in the L<Inbox>. Providing this ID allows you to pop open the inbox to a specific message to display to the user. The message will tell you what the outcome of the mission is if any. Not all missions will provide a message_id.

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 spy_id

The unique id of the spy you wish to assign.

=head3 assignment

A string containing the new assignment name. These are the possible assignments:

=over

=item Idle

Don't do anything.

=item Gather Shipping Intelligence

Find out what's up for trade, what ships are available, what ships are being built, where ships are travelling to, etc.

=item Gather Empire Intelligence

Find out what is built on this planet, the resources of the planet, what other colonies this Empire has, etc.

=item Gather Operative Intelligence

Find out what spies are on this planet, where they are from, what they are doing, etc.

=item Hack Network 19

Attempts to besmirch the good name of the empire controlling this planet, and deprive them of a small amount of happiness.

=item Appropriate Plans

Steal plans for buildings that this empire has built.

=item Sabotage Probes

Destroy probes controlled by this empire.

=item Rescue Comrades

Break spies out of prison.

=item Sabotage Ships

Destroy ships being built, docked, en route to mining platforms, etc.

=item Appropriate Ships

Steal empty ships, ships full of resources, ships full of trade goods, etc.

=item Assassinate Operatives

Kill spies.

=item Sabotage Infrastructure

Destroy buildings.

=item Incite Mutany

Turn spies. If successful they come work for you.

=item Incite Rebellion

Oblitterate the happiness of a planet. If done long enough, it can shut down a planet.

=back

B<NOTE:> You can do good things to enemies, and bad things to allies using these assignments.

=cut
