=head1 Intelligence Methods

Intelligence Ministry is accessible via the URL C</intelligence>.

The Intelligence Ministry is where you build and control your spies.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session_id, building_id )

 {
    "status" : { ... },
    "building" : { ... },
    "spies" : {
        "maximum" : 5,
        "current" : 1,
        "training_costs" : {
            "food" : 100,
            "water" : 120,
            "energy" : 20,
            "ore" : 5,
            "waste" : 10,
            "time" : 60,
        }
    },
 }
 

=head2 train_spy ( session_id, building_id, [ quantity ])

Allows you to train more spies.

 {
    "status" : { ... },
    "trained" : 3,
    "not_trained" : 2
 }
 
The only reason C<not_trained> might be over 0 is if you specify training more spies than you have resources to spend.

Throws 1013, 1009.

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 quantity

An integer between 1 and 5. Defaults to 1.


=head2 view_spies ( session_id, building_id, [ page_number ] )

Returns the list of spies you have on your roster.

 {
    "status" : { ... },
    "spies" : [
        {
            "id" : "id-goes-here",
            "name" : "Jason Bourne",
            "assignment" : "Idle",
            "assigned_to" : {
                "body_id" : "id-goes-here",
                "name" : "Earth",
            },
            "is_available" : 1, # can be reassigned
            "available_on" : "01 31 2010 13:09:05 +0600" # if can't be reassigned, this is when will be available
        },
        ...
    ],
    "spy_count" : 12,
    "possible_assignments" : [
        'Idle',
        'Gather Intelligence',
        ...
    ]
 }

Take a look at the C<assign_spy> method below for assignment descriptions.

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 page_number

Defaults to 1. An integer representing which page to view. Shows 25 spies per page.



=head2 burn_spy ( session_id, building_id, spy_id )

Allows you to eliminate one of your spies from your payroll.

 {
    "status" : { ... }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 spy_id

The unique id of the spy you wish to burn.


=head2 name_spy ( session_id, building_id, spy_id, name )

Set the name of the spy. Returns:

 {
    "status" : { ... }
 }
 
Throws 1002, 1005, 1013.

=head3 session_id

A session id.

=head3 building_id

The unique id of the intelligence building.

=head3 spy_id

The unique id of the spy you wish to train.

=head3 name

The name you'd like to set for the spy. The name cannot contain @, <, #, &, ; or profanity, and must be at least 1 character long.



=head2 assign_spy ( session_id, building_id, spy_id, assignment )

Set a spy on a new task.

=head3 session_id

A session id.

=head3 building_id

The unique id of your Intelligence Ministry.

=head3 spy_id

The unique id of the spy you wish to assign.

=head3 assignment

A string containing the new assignment name. These are the possible assignments:

=over

=item Idle

Don't do anything.

=item Gather Intelligence

Gather information about what is happening on this planet. On your own planets it will help you find out who's spying on you and what they're doing. On foreign planets it will give you information about the economy, infrastructure, and strength of that planet.

=item Capture Spies

Attempt to disrupt the plots of foreign spies on this planet.

=item Sabotage Infrastructure

Attempt to destroy things on the planet.

=item Appropriate Technology

Attempt to steal ships, buildings, and possibly resources.

=item Incite Rebellion

Attempt to deplete happiness, turn spies, and otherwise cause chaos amongst the population.

=item Hack Networks

Attempt to destroy or control probes, and spread misinformation through Network 19.

=back

B<NOTE:> You can do good things to enemies, and bad things to allies using these assignments.

=cut