=head1 Map Methods

These methods are accessible via the C</map> URL.

=head2 get_stars ( session_id, x1, y1, x2, y2, z )

Retrieves a chunk of the map and returns it as an array of hashes.

 [
    {
        "name"          : "Sol",
        "can_name"      : 1,
        "color"         : "yellow",
        "x"             : -41,
        "y"             : 27,
        "z"             : 14,
        "alignments"    : [ "self", "ally" ]
    }.
    {
        "name"          : "X143S",
        "can_name"      : 0,
        "color"         : "green",
        "x"             : -42,
        "y"             : 27,
        "z"             : 14,
        "alignments"    : [ "unprobed" ]
    }
 ]

The requested area can be no larger than 100 stars. Throws 1003 when the area is too large.

=head3 session_id

A session id.

=head3 x1

The top left x coord.

=head3 y1

The top left y coord.

=head3 x2

The bottom right x coord.

=head3 y2

The bottom right y coord.

=head3 z

The z axis. There's no secondary z coordinate because you can only pull from one z axis at a time.

=cut

