=head1 Mining Ministry Methods

Mining Ministry is accessible via the URL C</miningministry>.

The Mining Ministry controls mining platform ships for harvesting the resources of asteroids.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session_id, building_id )

Returns

 {
    "status" : { ... },
    "building" : { ... },
    "mining" : {
        "ships_in_fleet" : 1,
        "max_ships" : 2,
        "platforms_in_fleet" : 1,
        "max_platforms" : 1,
        "production" : {
            "rutile_hour" : 10,
            "chromite_hour" : 10,
            "chalcopyrite_hour" : 10,
            "galena_hour" : 10,
            "gold_hour" : 10,
            "uraninite_hour" : 10,
            "bauxite_hour" : 10,
            "goethite_hour" : 10,
            "halite_hour" : 10,
            "gypsum_hour" : 10,
            "trona_hour" : 10,
            "kerogen_hour" : 10,
            "methane_hour" : 10,
            "anthracite_hour" : 10,
            "sulfur_hour" : 10,
            "zircon_hour" : 10,
            "monazite_hour" : 10,
            "fluorite_hour" : 10,
            "beryl_hour" : 10,
            "magnetite_hour" : 10,  
        },
        "production_capacity" : 100, # expressed as a percentage
        "shipping_capacity" : 51 # expressed as a percentage
    }
 }
 
 
=head2 view_asteroids ( session_id, building_id )

Shows you the asteroids that you have mining platforms attached to.

 {
    "asteroids" : [
        "name" : "$roid->name,
        "id" : "id-goes-here",
        "x" : 1,
        "y" : -7,
        "z" : 4,
        "orbit" : 4,
        "image" : "a3",
        "platform_count" : 1 
    ],
    "status" : { get_status() }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the mining ministry.



=head2 add_cargo_ship_to_fleet ( session_id, building_id, ship_count )

Take a cargo ship from the space port and add it to the mining fleet.

 {
    "status" : { get_status() }
 }
 
Throws 1009.

=head3 session_id

A session id.

=head3 building_id

The unique id of the mining ministry.

=head3 ship_count

The number of ships you wish to add.



=head2 remove_cargo_ship_from_fleet ( session_id, building_id, ship_count )

Tell one of the cargo ships in the mining fleet to come home and park at the space port.

 {
    "status" : { get_status() }
 }
 
Throws 1009.

=head3 session_id

A session id.

=head3 building_id

The unique id of the mining ministry.

=head3 ship_count

The number of ships you wish to remove.



=head2 abandon_platform ( session_id, building_id, asteroid_id )

Close down an existing mining platform.

 {
    "status" : { get_status() }
 }
 
Throws 1002.

=head3 session_id

A session id.

=head3 building_id

The unique id of the mining ministry.

=head3 asteroid_id

The unique id of the asteroid from which you wish to abandon a mining platform.

=cut
