=head1 Observatory Methods

Observatory is accessible via the URL C</observatory>.

The observatory controls stellar probes.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.



=head2 get_probed_stars ( session_id, building_id, [ page_number ] )

Returns a list of the stars that have been probed by this planet.

 {
	"status" : { ... },
    "stars" : [
        "id" : "id-goes-here",
		"color" : "yellow",
		"name" : "Sol",
		"x" : 17,
		"y" : 4,
		"z" : -3,
		"bodies" : [
            { See get_status() in Body },
            ...
        ]
	],
    "star_count" : 37
 }


=head3 session_id

A session id.

=head3 building_id

The unique id for the observatory.

=head3 page_number.

An integer representing which set of probes to return. Defaults to 1. Each page has up to 25 probes.



=head2 abandon_probe ( session_id, building_id, star_id )

The probe is deactivated, and allowed to burn up in the star.

 {
	"status" : { ... }
 }

Throws 1002, 1010.

=head3 session_id

A session id.

=head3 building_id

The unique id for the observatory.

=head3 star_id

The unique id of the star the probe is attached to.


=cut
