=head1 Oversight Ministry Methods

The Oversight Ministry is accessible via the URL C</oversight>. It is used to speed up the construction and upgrade of buildings through better project management. The time cost of all buildings is reduced by 1% per level of the Oversight Ministry.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=cut
