=head1 Parliament Methods

Parliament is accessible via the URL C</parliament>.

The list of methods below represents changes and additions to the methods that all L<Modules> share.

Note: all of the voting API calls have now been moved to the L<Embassy>.













=head2 view_taxes_collected (session_id, building_id )

Returns a list of the empires that have paid taxes and how much has been paid for the past seven days.

Within the taxes_collected list you will find the id and name of the empire that paid taxes, a list of payments for today (element 0) and the previous six days as well as the total of those seven days payments.

 {
    "status" : { ... },
    "taxes_collected" : [
        {
           "id" : "id-goes-here",
           "name" : "Klingons",
           "paid" : [ 0, 1000, 0, 0, 1500, 500, 500 ],
           "total" : 3500,
        },
        ...
    ]
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.









=head2 propose_taxation ( session_id, building_id, taxes )

Introduces an unenforceable law that imposes a tax on all empires under the jurisdiction of the space station. Usable at parliament level 15.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Tax of 5000 resources per day",
        "description" : "Implement a tax of 5000 resources per day for all empires in the jurisdiction of this station",
        "votes_needed" : 7,
        "votes_yes" : 0,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Klingons",
        }
    }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 taxes

The amount of taxes to impose per day.





=head2 propose_foreign_aid ( session_id, building_id, planet_id, resources )

Sends a foreign aid package to a planet in the jurisdiction of the station. The foreign aid is sent via supply pod. Usable at parliament level 16.

The foreign aid package costs double whatever aid is being sent. The first half to cover the cost of the supply pod, the second half is the resources being sent. Just like with normal supply pods, no more than one per day.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Foreign Aid for Kronos",
        "description" : "Send a foreign aid package of 10000 resources to Kronos (total cost 20000 resources).",
        "votes_needed" : 7,
        "votes_yes" : 0,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Klingons",
        }
    }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 planet_id

The unique id of the planet to receive the foreign aid package.

=head3 resources

The amount of resources to send to the receiving planet.




=cut
