=head1 Parliament Methods

Parliament is accessible via the URL C</parliament>.

The list of methods below represents changes and additions to the methods that all L<Modules> share.


=head2 view_propositions (session_id, building_id )

Returns a list of the pending propositions.

 {
    "status" : { ... },
    "propositions" : [
        {
           "id" : "id-goes-here",
           "name" : "Rename Station",
           "description" : "Rename the station from 'Bri Prui 7' to 'Deep Space 1'.",
           "votes_needed" : 7,
           "votes_yes" : 1,
           "votes_no" : 0,
           "status" : "Pending",
           "date_ends" : "01 31 2010 13:09:05 +0600",
           "proposed_by" : {
                "id" : "id-goes-here",
                "name" : "Klingons",
           },
           "my_vote" : 0 # not present if they haven't voted
        },
        ...
    ]
 }
 
=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.





=head2 cast_vote ( session_id, building_id, proposition_id, vote )

Casts a vote for or against a proposition. Cannot be voted on using a sitter password.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Rename Station",
        "description" : "Rename the station from 'Bri Prui 7' to 'Deep Space 1'.",
        "votes_needed" : 7,
        "votes_yes" : 2,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Klingons",
        },
        "my_vote" : 0 # not present if they haven't voted
    }
 }


=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 proposition_id

The id of the propostion your casting this vote for or against. See C<view_propositions> for a list.

=head3 vote

A boolean indicating which way you wish to vote. 1 for yes. 0 for no. Default is 0.

=cut