=head1 Parliament Methods

Parliament is accessible via the URL C</parliament>.

The list of methods below represents changes and additions to the methods that all L<Modules> share.


=head2 view_laws (session_id, body_id )

B<NOTE:> Pass in a the id of the station, not the id of the parliament building. This is because anyone that wants to should be able to view the laws in this jurisdiction.

Returns a list of the laws.

 {
    "status" : { ... },
    "laws" : [
        {
            "id" : "id-goes-here",
            "name" : "Centure of Jamie Vrbsky",
            "description" : "Jamie Vrbsky is bad at playing Lacuna!",
            "date_enacted" : "01 31 2010 13:09:05 +0600"
        },
        ...
    ]
 }
 
=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.





=head2 view_propositions (session_id, building_id )

Returns a list of the pending propositions.

 {
    "status" : { ... },
    "propositions" : [
        {
           "id" : "id-goes-here",
           "name" : "Rename Station",
           "description" : "Rename the station from 'Bri Prui 7' to 'Deep Space 1'.",
           "votes_needed" : 7,
           "votes_yes" : 1,
           "votes_no" : 0,
           "status" : "Pending",
           "date_ends" : "01 31 2010 13:09:05 +0600",
           "proposed_by" : {
                "id" : "id-goes-here",
                "name" : "Klingons",
           },
           "my_vote" : 0 # not present if they haven't voted
        },
        ...
    ]
 }
 
=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.





=head2 cast_vote ( session_id, building_id, proposition_id, vote )

Casts a vote for or against a proposition. Cannot be voted on using a sitter password.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Rename Station",
        "description" : "Rename the station from 'Bri Prui 7' to 'Deep Space 1'.",
        "votes_needed" : 7,
        "votes_yes" : 2,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Klingons",
        },
        "my_vote" : 0 # not present if they haven't voted
    }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 proposition_id

The id of the propostion your casting this vote for or against. See C<view_propositions> for a list.

=head3 vote

A boolean indicating which way you wish to vote. 1 for yes. 0 for no. Default is 0.



=head1 Proposition Methods

The following methods propose laws or actions to be taken by the station on behalf of Parliament. There are many propositions that are implied, such as installing a new module or renaming the station. These propositions, must be explicitly declared through parliament by calling these methods.


=head2 propose_writ ( session_id, building_id, title, description )

Proproses an unenforceable law. Only works with Parliament 4 and higher.

B<NOTE:> See the C<writ_templates> section of C<resources.json>. These should be included as selectable options as a way to start the writeup of a title and description for a writ.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Centure of Jamie Vrbsky",
        "description" : "Jamie Vrbsky is bad at playing Lacuna!",
        "votes_needed" : 7,
        "votes_yes" : 0,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Klingons",
        }
    }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 target_x, target_y

The C<x,y> coordinates of the planet that is the target.

=head3 reason

An explict reason why the BFG should be fired upon the target. Same rules as an L<Inbox> message body apply here.





=head2 propose_transfer_station_ownership ( session_id, building_id, to_empire_id )

Transfer the ownership of the station to another member of the alliance. Only works with Parliament 6 and higher.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Transfer Station",
        "description" : "Transfer ownership of Deep Space 9 from The Federation to the Klingon Empire.",
        "votes_needed" : 7,
        "votes_yes" : 0,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Klingons",
        }
    }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 to_empire_id

The id of an empire within the alliance that wants control over the station.



=head2 propose_fire_bfg ( session_id, building_id, target_x, target_y, reason )

Fires the BFG equipped on all space stations at a planet of Parliament's choosing as long as it is within the jurisdiction of the station. Can only be called by Parliament level 30.

 {
    "status" : { ... },
    "proposition" : {
        "id" : "id-goes-here",
        "name" : "Fire BFG",
        "description" : "Fire BFG at Alderaan from The Death Star. Reason cited: The princess isn't talking!",
        "votes_needed" : 7,
        "votes_yes" : 0,
        "votes_no" : 0,
        "status" : "Pending",
        "date_ends" : "01 31 2010 13:09:05 +0600",
        "proposed_by" : {
             "id" : "id-goes-here",
             "name" : "Admiral Motti",
        }
    }
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the parliament.

=head3 target_x, target_y

The C<x,y> coordinates of the planet that is the target.

=head3 reason

An explict reason why the BFG should be fired upon the target. Same rules as an L<Inbox> message body apply here.

=cut