=head1 Planetary Command Methods

Planetary Command Center is accessible via the URL C</planetarycommand>.

The Planetary Command Center (PCC), or just Command, is the hub of your empire on a planet. It gives you the resources and storage you need to get a foothold on a planet.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session_id, building_id )

Command extends the view method to include a C<planet> section.

 {
    "building" : { ... },
    "status" : { ... },
    "next_colony_cost" : 750000,        # the amount of happiness required to settle your next colony
    "planet" : {
        "id" : "id-goes-here",
        "x" : -4,
        "y" : 10,
        "z" : 6,
        "star_id" : "id-goes-here",
        "orbit" : 3,
        "type" : "habitable planet",
        "name" : "Earth",
        "image" : "p13",
        "size" : 67,
        "water" : 900,
        "ore" : {
            "gold" : 3399,
            "bauxite" : 4000,
            ...
        },
        "building_count" : 7,
        "population" : 470000,
        "happiness" : 3939,
        "happiness_hour" : 25,
        "food_stored" : 33329,
        "food_capacity" : 40000,
        "food_hour" : 229,
        "energy_stored" : 39931,
        "energy_capacity" : 43000,
        "energy_hour" : 391,
        "ore_hour" 284,
        "ore_capacity" 35000,
        "ore_stored" 1901,
        "waste_hour" : 933,
        "waste_stored" : 9933,
        "waste_capacity" : 13000,
        "water_stored" : 9929,
        "water_hour" : 295,
        "water_capacity" : 51050
    }
 }

=cut