=head1 PoliticsTraining Methods

Politics Training Facility is accessible via the URL C</politicstraining>.

The Politics Training Facility is where you train your spies in the dark art of social engineering.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session_id, building_id )

 {
    "status" : { ... },
    "building" : { ... },
    "spies" : {
        "maximum" : 5,
        "current" : 1,
        "in_training" : 1,
        "training_costs" : {
            "food" : 100,
            "water" : 120,
            "energy" : 20,
            "ore" : 5,
            "waste" : 10,
            "time" : [
                {
                    "spy_id" : "1",
                    "time" : "18720",
                },
                ...
            ],
        }
    },
 }
 

=head2 train_spy ( session_id, building_id, spy_id )

Allows you to train an idle spy in the dark art of social engineering.

The trained spy will receive 1 politics per level of the building.

 {
    "status" : { ... },
    "trained" : 1,
    "not_trained" : 0
 }
 
The only reason C<not_trained> might be over 0 is if you specify training more spies than you have resources to spend.

Throws 1013, 1009.

=head3 session_id

A session id.

=head3 building_id

The unique id of your Politics Training Facility.

=head3 spy_id

The unique id of the spy to train.





=head2 view_spies ( session_id, building_id, [ page_number ] )

Returns the list of spies you have on your roster that are present.

 {
    "status" : { ... },
    "spies" : [
        {
            "id" : "id-goes-here",
            "name" : "Jason Bourne",
            "assignment" : "Idle",
            "level" : 9,
            "politics" : 0,                         # experience in handling happiness
            "mayhem" : 20,                          # experience in handling missions involving murder and destruction
            "theft" : 40,                           # experience in handling missions involving stealing items
            "intel" : 33,                           # experience in handling missions involving information and spies
            "offense_rating" : 570,
            "defense_rating" : 150,
            "assigned_to" : {
                "body_id" : "id-goes-here",
                "name" : "Earth",
                "x" : 40,
                "y" : -71
            },
            "is_available" : 1, # can be reassigned
            "available_on" : "01 31 2010 13:09:05 +0600", # if can't be reassigned, this is when will be available
            "started_assignment" : "01 31 2010 13:09:05 +0600",
            "seconds_remaining" : 45,
			"mission_count" : {
				"offensive" : 149,
				"defensive" : 149
			}
        },
        ...
    ],
    "spy_count" : 12
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of your Politics Training Facility.

=head3 page_number

Defaults to 1. An integer representing which page to view. Shows 25 spies per page.



=cut
