=head1 Shipyard Methods

Shipyard is accessible via the URL C</shipyard>.

The shipyard is where you build ships. However, you'll need other building types to enable the different kinds of ships that are available. The higher the level of the shipyard, faster your ships will be built.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

 
=head2 view_build_queue ( session_id, building_id, [page_number])

Retrieves what is already being built at this shipyard.

 {
     "status" : { ... },
     "number_of_ships_building" : 30,
     "ships_building" : [
         {
             "type" : "spy_pod",
             "date_completed" : "01 31 2010 13:09:05 +0600"
         }
         ...
     ]
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of this shipyard.

=head3 page_number.

Defaults to 1. An integer representing the page of data to view. There are 25 items per page.
 
 
=head2 get_buildable ( session_id, building_id )

Returns a list of buildable ships and their costs, and if they're not buildable, gives a reason why not in the form of an exception.

 {
    "buildable" : {
        "probe" : {
            "can" : 1,             # can it be built or not
            "reason" : null,       # if it can't an array ref will be here with the exception for why not
            "cost" : {
                "seconds" : 900,
                "food" : 1100,
                "water" : 1000,
                "energy" : 1200,
                "ore" : 1200,
                "waste" : 100,
            },
            attributes : {
                "speed" : 1000,    # 100 roughly equals 1 star in 1 hour
            }
        },
        ...
    },
    "docks_available" : 7,         # you can only build ships up to the number of docks you have available
    "status" : { ... },
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the shipyard.


 
 
=head2 build_ship ( session_id, building_id, type )

Adds a ship to the build queue. Returns the same thing as C<view_build_queue()>.

=head3 session_id

A session id.

=head3 building_id

The unique id of the shipyard.

=head3 type

A ship type. Choose from: 'probe','colony_ship','spy_pod','cargo_ship','space_station','smuggler_ship','mining_platform_ship','terraforming_platform_ship', or 'gas_giant_settlement_ship'.

=cut
