=head1 Ship Descriptions

Ship descriptions are bulky, and are the same every time. As such we've created a file you can download to include ship descriptions in your client. You should cache this file once you've downloaded and only get it again if it has changed.

 https://servername.lacunaexpanse.com/resources.json

=head1 Shipyard Methods

Shipyard is accessible via the URL C</shipyard>.

The shipyard is where you build ships. However, you'll need other building types to enable the different kinds of ships that are available. The higher the level of the shipyard, faster your ships will be built.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

 
=head2 view_build_queue ( session_id, building_id, [page_number])

Retrieves what is already being built at this shipyard.

 {
     "status" : { ... },
     "number_of_ships_building" : 30,
     "cost_to_subsidize" : 30,
     "ships_building" : [
         {
             "id" : "1234",
             "type" : "spy_pod",
             "type_human" : "Spy Pod",
             "date_completed" : "01 31 2010 13:09:05 +0600"
         }
         ...
     ]
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of this shipyard.

=head3 page_number.

Defaults to 1. An integer representing the page of data to view. There are 25 items per page.
 
 
 
=head2 subsidize_build_queue ( session_id, building_id )

Will spend 1 essentia per ship to complete the current build queue immediately. Returns C<view>.

Throws 1011.

=head3 session_id

A session id.

=head3 building_id

The unique id of the Shipyard.

 
=head2 subsidize_ship ( parameter_hash )

Will spend 1 essentia to complete the build of the specified ship.

This accepts a hash of named arguments.

  {
    "session_id"    : 1234-123-123,
    "building_id"   : 4567,
    "ship_id"       : 88478,
  }

Throws 1011.

=head3 session_id (required)

A session id.

=head3 building_id (required)

The unique id of the Shipyard.

=head3 ship_id (required)

The unique id of the Ship, as returned in C<view_build_queue>

=head3 RESPONSE

Returns the same as C<view_build_queue>

=head2 get_buildable ( session_id, building_id, [ tag ] )

Returns a list of buildable ships and their costs, and if they're not buildable, gives a reason why not in the form of an exception.

 {
    "buildable" : {
        "probe" : {
            "can" : 1,             # can it be built or not
            "reason" : null,       # if it can't an array ref will be here with the exception for why not
            "cost" : {
                "seconds" : 900,
                "food" : 1100,
                "water" : 1000,
                "energy" : 1200,
                "ore" : 1200,
                "waste" : 100,
            },
            attributes : {
                "speed" : 1000,    # 100 roughly equals 1 star in 1 hour
                "hold_size" : 1000,
                "max_occupants" : 2,
                "combat" : 0,
                "stealth" : 1500
            }
        },
        ...
    },
    "docks_available" : 7,         # you can only build ships up to the number of docks you have available
    "build_queue_max" : 60,        # maximum queueable ships
    "build_queue_used" : 3,        # ships in queue for all shipyards
    "status" : { ... },
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of the shipyard.

=head3 tag

An optional tag to limit the list of available ships to something shorter. If no tag is specified, then all ships will be displayed.

=over

=item Trade

Ships that can be used to carry resources between colonies.

=item Colonization

Ships used to get more planets.

=item Intelligence

Ships that deal with spies or intelligence gathering.

=item Exploration

Ships that allow the user to go out and explore the Expanse.

=item War

Ships that are used to attack or defend.

=item Mining

Ships that are used to gather resources from space.

=back

=head2 build_ship ( session_id, building_id, type, [ quantity ] )

Adds ships to the build queue. Returns the same thing as C<view_build_queue()>.

=head3 session_id

A session id.

=head3 building_id

The unique id of the shipyard.

=head3 type

A ship type. Get from C<get_buildable>.

=head3 quantity

An optional quantity, if left blank it defaults to 1, otherwise specify the number
of ships to build up to a maximum of 600. You must have the shipyard capacity, the
space port capacity and the resources required to build the specified quantity of
ships.

=head2 build_ships ( session_id, options )

Adds ships to build queues. Returns only the empire status.

=head3 session_id

A session id.

=head3 options

A hash of options.  Keys are:

=over 4

=item type

A ship type. Get from C<get_buildable>.

=item quantity

An optional quantity.  If omitted, it defaults to 1, otherwise specify the
number of ships to build up to a maximum of 600.  You must have the shipyard
capacity, space port capacity, and the resources required to build the
specified quantity of ships.  For now, you must be able to build this quantity
as if it were all at the highest shipyard in your queue, which should only
be an issue if you're almost out of resources.

=item body_id

When selecting C<all> shipyards, can simply provide the body_id to save
the extra RPC call to look for all shipyards and select one.  At least one
of body_id and building_id must be provided.

=item building_id

Can be a single building ID of the shipyard, or an array of building IDs to
select which shipyards to use.  All buildings must belong to the same body.
If the C<body_id> is also set, all shipyards must be on that body.  At least
one of body_id and building_id must be provided.

=item autoselect

The shipyard autoselect mode.  By default, if this is not set, the mode
is to only use the shipyard(s) selected by building_id.

Can be one of:

=over 4

=item 1.

C<all>

Selects all shipyards on the current body, whether that was from body_id or
building_id(s).

=item 2.

C<higher>

Selects all shipyards on the current body, whose level is I<equal to or higher than>
the building_id passed in.  Cannot pass in multiple building_ids when
using this option.

=item 3.

C<only>

Selects all shipyards on the current body, whose level is I<only equal to>
the building_id passed in.  Cannot pass in multiple building_ids when
using this option.

=back

=back

=cut
