=head1 TheftTraining Methods

Theft Training Facility is accessible via the URL C</thefttraining>.

The Theft Training Facility is where you train your spies in the art of appropriation.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.

=head2 view ( session_id, building_id )

 {
    "status" : { ... },
    "building" : { ... },
    "spies" : {
        "max_points" : 2600,
        "points_per" : 45,
        "in_training" : 4,
    },
 }

=head3 session_id

A session id.

=head3 building_id

The unique id of your Theft Training Facility.

=cut
